default_language_version:
    python: python3.8

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: requirements-txt-fixer
          - id: name-tests-test
            exclude: '.*\/examples\/.*'
          - id: forbid-new-submodules
          - id: check-yaml
            args:
                - --unsafe
            files: (\.(yaml|yml|eyaml))$
            exclude: (^deploy\/[a-z|A-Z|0-9|\/|_|\-|\.]+\.(yaml|yml|eyaml))$
          - id: check-json
            files: \.(jshintrc|json)$
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.5.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/asottile/pyupgrade
      rev: v1.25.2
      hooks:
          - id: pyupgrade
            args:
                - --py3-plus
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.2.3
      hooks:
          - id: add-trailing-comma
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: debug-statements
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args:
                - --safe
                - --line-length
                - "100"
